# Generated by Django 3.2.18 on 2023-05-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://media.istockphoto.com/id/177370583/photo/traffic-cones-and-hardhat-3d-isolated.jpg?s=612x612&w=0&k=20&c=RDDLHMULBB-G_FMMijdavKuVkpYnLIRCbAA1a41r-7o=', max_length=200),
        ),
    ]
